apiVersion: apps/v1
kind: Deployment
metadata:
  name: colorballs-nginx
  labels: 
    app: colorballs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: colorballs-app
  template:
    metadata:
      labels:
        app: colorballs-app
        role: rolling-update
    spec:
      containers:
      - name: colorballs-container
        image: radhatiwari/deployk8s_nginx:1.0
        imagePullPolicy: "Always"
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1