apiVersion: apps/v1
kind: Deployment
metadata:
  name: colorballs-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: color-balls
  template:
    metadata:
      labels:
        app: color-balls
    spec:
      containers:
      - name: color-balls
        image: radhatiwari/k8s-deploy:orange
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: colorball-svc
spec:
  selector:
    app: color-balls
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: NodePort
